name: project-atlas-ci
on: [push]
jobs:
  python-code-check:
    name: Checking Python Code...
    runs-on: ubuntu-latest
    steps:
      - name: Checking-out commit code...
        uses: actions/checkout@v3
      - name: Installing OS prerequisites...
        run:  sudo apt-get update && sudo apt-get install -y --no-install-recommends libmagic1
      - name: Setting-up Python environment...
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Creating test directories...
        run:  mkdir -p /tmp/pytest
      - name: Installing python dependencies...
        run:  |
          python -m pip install --no-cache-dir --upgrade pip
          pip install --no-cache-dir --upgrade -r builder/requirements-api.txt
          pip install --no-cache-dir --upgrade -r builder/requirements-tests.txt
      - name: Running unit tests...
        working-directory: ./app
        run:  pytest -v --basetemp /tmp/pytest
        env:
          FILES_API_PRIVATE_JWK: ${{ secrets.FILES_API_PRIVATE_JWK }}
          FILES_API_PUBLIC_JWK:  ${{ secrets.FILES_API_PUBLIC_JWK }}
          FILES_API_ALLOWED_AUD: '["sample-platform"]'
          FILES_API_ALLOWED_SUB: '["sample-id"]'
          FILES_API_LIBRARY_DIR: "/tmp/pytest"
          FILES_API_FILES_DIR:   "/tmp/pytest"

  docker-build-image-debian:
    name: Building docker image [debian]...
    needs: python-code-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit code
        uses: actions/checkout@v3
      - name: Build docker image
        run:  docker build -f builder/Dockerfile.debian .

  docker-build-image-alpine:
    name: Building docker image [alpine]...
    needs: python-code-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout commit code
        uses: actions/checkout@v3
      - name: Build docker image
        run:  docker build -f builder/Dockerfile.alpine .
